apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: go-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: REGION
          value: "us-west-2"
        - name: SQS_QUEUE_URL
          value: "https://sqs.us-west-2.amazonaws.com/your-account-id/nodejs_to_go"
        - name: RDS_USER
          value: "admin"
        - name: RDS_PASSWORD
          value: "password"
        - name: RDS_HOST
          value: "your-rds-endpoint"
        - name: RDS_DATABASE
          value: "your-database-name"