apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server
        image: go-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: REGION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_REGION
        - name: SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SQS_NODEJS_TO_GO_URL
        - name: RDS_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RDS_USER
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RDS_PASSWORD
        - name: RDS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RDS_HOST
        - name: RDS_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RDS_DATABASE