apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: nodejs:latest
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_REGION
        - name: DYNAMODB_TABLE
          value: "syllables"
        - name: GO_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SQS_GO_TO_PYTHON_URL