apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-server
  template:
    metadata:
      labels:
        app: nodejs-server
    spec:
      containers:
      - name: nodejs-server
        image: nodejs:latest
        ports:
        - containerPort: 3000
        env:
        - name: AWS_REGION
          value: "us-west-2"
        - name: DYNAMODB_TABLE
          value: "syllables"
        - name: GO_QUEUE_URL
          value: "https://sqs.us-west-2.amazonaws.com/your-account-id/go_to_python"