apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: AWS_REGION
        - name: SQS_NODEJS_TO_GO_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SQS_NODEJS_TO_GO_URL
        - name: SQS_GO_TO_PYTHON_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SQS_GO_TO_PYTHON_URL