- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create Node.js Docker Compose file
  copy:
    dest: /opt/nodejs/docker-compose.yml
    content: |
      version: '3'
      services:
        nodejs:
          image: nodejs:latest
          ports:
            - "3000:3000"
          environment:
            - AWS_REGION={{ vault_vars.aws_region }}
            - DYNAMODB_TABLE={{ vault_vars.dynamodb_table }}
            - GO_QUEUE_URL={{ vault_vars.go_queue_url }}

- name: Start Node.js server
  command: docker-compose up -d
  args:
    chdir: /opt/nodejs