- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create Go server Docker Compose file
  copy:
    dest: /opt/go/docker-compose.yml
    content: |
      version: '3'
      services:
        go-server:
          image: go-server:latest
          ports:
            - "8080:8080"
          environment:
            - REGION={{ vault_vars.aws_region }}
            - SQS_QUEUE_URL={{ vault_vars.sqs_queue_url }}
            - RDS_USER={{ vault_vars.rds_user }}
            - RDS_PASSWORD={{ vault_vars.rds_password }}
            - RDS_HOST={{ vault_vars.rds_host }}
            - RDS_DATABASE={{ vault_vars.rds_database }}

- name: Start Go server
  command: docker-compose up -d
  args:
    chdir: /opt/go