- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create Go server Docker Compose file
  copy:
    dest: /opt/go/docker-compose.yml
    content: |
      version: '3'
      services:
        go-server:
          image: go-server:latest
          ports:
            - "8080:8080"
          environment:
            - REGION=us-west-2
            - SQS_QUEUE_URL=https://sqs.us-west-2.amazonaws.com/your-account-id/nodejs_to_go
            - RDS_USER=admin
            - RDS_PASSWORD=password
            - RDS_HOST=your-rds-endpoint
            - RDS_DATABASE=your-database-name

- name: Start Go server
  command: docker-compose up -d
  args:
    chdir: /opt/go