apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080