apiVersion: v1
kind: Service
metadata:
  name: nodejs-server-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000