apiVersion: v1
kind: Service
metadata:
  name: python-server-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: python-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80