- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Install Docker-Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Create FastAPI Docker Compose file
  copy:
    dest: /opt/fastapi/docker-compose.yml
    content: |
      version: '3'
      services:
        fastapi:
          image: fastapi:latest
          ports:
            - "80:80"
          environment:
            - AWS_REGION=us-west-2
            - SQS_NODEJS_TO_GO_URL=https://sqs.us-west-2.amazonaws.com/your-account-id/nodejs_to_go
            - SQS_GO_TO_PYTHON_URL=https://sqs.us-west-2.amazonaws.com/your-account-id/go_to_python

- name: Start FastAPI server
  command: docker-compose up -d
  args:
    chdir: /opt/fastapi