name: CI for python folder

on:
  push:
    paths:
      - 'python/**'
  pull_request:
    paths:
      - 'python/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt  # Asumiendo que tienes un requirements.txt en la carpeta python

    - name: Run unit tests
      run: |
        cd python
        python -m unittest test_main.py

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  

    - name: Install SonarCloud scanner
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d $HOME
        export PATH=$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin

    - name: Run SonarCloud scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
      run: |
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.organization=your_organization \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: sonarcloud  
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git checkout main
        git merge ${{ github.head_ref }}
        git push origin main